#!/bin/bash

# backs up a juniper switch that doesn't exist anymore :D

BACKUPDIR="${YALEMAN_BACKUP_DIR:?Set YALEMAN_BACKUP_DIR as an env var}/ex3300/$(date +%Y-%m-%d-%H%M%S)"

mkdir -p "${BACKUPDIR}"

cd "${BACKUPDIR}" || exit 1

echo "Backing up to ${BACKUPDIR}"

echo "requesting rescue configuration"
ssh ex3300.housenet.yaleman.org request system configuration rescue save
echo "testing rescue configuration"
ssh ex3300.housenet.yaleman.org test configuration /config/rescue.conf.gz
echo "copying files..."
scp -r ex3300.housenet.yaleman.org:/config/rescue.conf.gz .
scp -r ex3300.housenet.yaleman.org:/config/juniper.conf.gz .


echo "Showing files"
find "${BACKUPDIR}" -type f -ls

echo "Done!"
