#!/bin/bash

set -ueo pipefail

HOSTNAME="${1:-c3650.housenet.yaleman.org}"
BACKUPDIR="${YALEMAN_BACKUP_DIR:?Set YALEMAN_BACKUP_DIR as an env var}/${HOSTNAME}"
BACKUPFILE="${BACKUPDIR}/$(date +%Y-%m-%d-%H%M%S).conf.gz"
mkdir -p "${BACKUPDIR}"

cd "${BACKUPDIR}" || exit 1

echo "Backing up to ${BACKUPFILE}"

echo "Backing up config..."
ssh "${HOSTNAME}" show running-config | gzip > "${BACKUPFILE}"

echo "Showing files"
find "${BACKUPDIR}" -type f -ls

echo "Done!"
