#!/bin/bash


if [[ " $* " =~ " --watch " ]]; then
  while true; do
    clear
    RES=$(badpods)
    if [[ -n "$RES" ]]; then
      echo "$RES"
    else
        echo "No bad pods found."
        exit 0
    fi
    sleep 5
  done
else
    RES=$(kubectl get pods -A | rg -v '(Running|Completed|NAMESPACE)')
    if [[ -n "$RES" ]]; then
      echo "$RES"
      exit 1
    else
        exit 0
    fi
fi
