#!/bin/bash

set -e

# the dotfiles dir
MYDIR="$(dirname "${0}")"

echo "Backing up Homebrew packages to $MYDIR/Brewfile"
HOMEBREW_NO_AUTO_UPDATE=1 brew bundle dump --force --file="$MYDIR/Brewfile"
# shellcheck disable=SC2181
if [ $? -eq 0 ]; then
    echo "Backup successful."
else
    echo "Backup failed."
fi
