#!/bin/bash

# does rust coverage things

set -e

if [ "$(which cargo)" == "" ]; then
    echo "cargo not found. Please install cargo"
    exit 1
fi

if [ ! -f 'Cargo.toml' ]; then
    echo "This script must be run from the root of a project"
    exit 1
fi

if [ ! -d './target/' ]; then
    echo "Are we in a rust project? No target directory found"
fi


cargo tarpaulin --exclude-files src/main.rs --out=Html
echo
echo "Coverage report is at  ./tarpaulin-report.html"