#!/usr/bin/env bash



TOTAL_MB=$(du -d1 -m -c "$HOME/Library/Application Support/Codex/Crashpad/" | tail -1 | awk '{print $1}')
OVERSIZE=1024
if [ "$TOTAL_MB" -gt "$OVERSIZE" ]; then
    echo "Codex Crashpad folder is larger than ${OVERSIZE}MB. Cleaning up..."
    rm -rf "$HOME/Library/Application Support/Codex/Crashpad"/*
else
    echo "Codex Crashpad folder size is under limits (${OVERSIZE}MB) ${TOTAL_MB}MB."
fi