#!/bin/bash

set -e

MYBRANCH="$(git branch --show-current)"

if [ -z "${MYBRANCH}" ]; then
    echo "Not on a branch, exiting"
    exit 1
fi

if [ "$(git remote -v | grep -ce "^upstream")" -eq 0 ]; then
    echo "Couldn't find an upstream remote, bailing"
    exit 1
fi

DEFAULT_BRANCH="$(gh repo view --json defaultBranchRef | jq -r .defaultBranchRef.name)"

if [ -z "${DEFAULT_BRANCH}" ]; then
    echo "Couldn't find the default branch using , bailing"
    echo "Tried this command: gh repo view --json defaultBranchRef"
    gh repo view --json defaultBranchRef
    exit 1
fi

git fetch upstream || exit 1

echo "Switching to ${DEFAULT_BRANCH}"
git switch "${DEFAULT_BRANCH}" || exit 1

echo "Resetting to ${DEFAULT_BRANCH}"
git reset --hard "upstream/${DEFAULT_BRANCH}"

git gc
