#!/bin/bash

MYBRANCH="$(git branch --show-current)"

if [ -z "${MYBRANCH}" ]; then
    echo "Not on a branch, exiting"
    exit 1
fi

if [ "$(git remote -v | grep upstream | grep push -c)" -ne 1 ]; then
    echo "Couldn't find an upstream remote, bailing"
    exit 1
fi

git switch "upstream/${MYBRANCH}" --detach || echo "Already in detached state"

git branch -D "${MYBRANCH}"

git checkout -b "${MYBRANCH}" && git pull upstream "${MYBRANCH}"

git gc
