#!/opt/homebrew/bin/bash

set -e

if [ -z "${1}" ]; then
	git status | rg 'modified:' \
		| awk '{print $2}' | rg '^\S+$' \
		| xargs -n1 git-diff-file-size
	exit 0
fi

if [ -d "${1}" ]; then
	# echo "Passed a dir!"
	git -C "${1}" status | rg 'modified:' \
		| awk '{print $2}' | rg '^\S+$' \
		| xargs -I{} git-diff-file-size "${1}/{}"
	exit 0
fi

if [ "$(echo -n "${1}" | sed -e 's/[[:space:]]//' | wc -c)" -eq 0 ]; then
	echo "git-diff-file-size was passed an empty string!" >&2
	exit 0
fi

file_path="$1"
if [ -n "${DEBUG}" ]; then
	echo "git-diff-file-size '$1'"
fi
# exit 0

if [ ! -e "$1" ]; then
	echo "'$1' doesn't exist!"
	exit 1
fi

if [ "$(which git-file-ref | wc -l)" -eq 0 ]; then
	echo "Can't find git-file-ref!"
	exit 1
fi

# text files
export GIT_PAGER=cat
REMOVALS="$(git diff --text "${file_path}" \
	| rg --text '^-' \
	| rg --text -v '^--- a' \
	| dd 2>&1 \
	| tail -n1 \
	| awk '{print $1}')"
ADDITIONS="$(git diff --text "${file_path}" \
	| rg --text '^\+' \
	| rg --text -v '^\+\+\+ b' \
	| dd 2>&1 \
	| tail -n1 \
	| awk '{print $1}')"
echo "REM: ${REMOVALS} ADD: ${ADDITIONS}"
difference=$((ADDITIONS-REMOVALS))
if [ "${difference}" -le 0 ]; then
	difference_check=$((difference * -1))
else
	difference_check=$((difference))
fi

if [ $((difference_check)) -gt 1024 ]; then
	difference=$(echo "scale=2; ${difference} / 1024" | bc)
	difference_unit="KB"
elif [ $((difference_check)) -gt 1048576 ]; then
	difference=$(echo "scale=2; ${difference} / 1048576" | bc)
	difference_unit="MB"
else
	difference_unit="B"
fi

FILE_SIZE="$(wc -c "${file_path}" | awk '{print $1}')"
ratio=$((100 * (difference_check / FILE_SIZE)))
if [ $((ADDITIONS)) -gt $((REMOVALS)) ]; then
	RATIO_MOD="+"
	COLOUR='\e[1;31m'
else
	RATIO_MOD="-"
	COLOUR='\e[1;32m'
fi
echo -e "${COLOUR}${difference}${difference_unit} \e[0m \t${RATIO_MOD}${ratio}% \t${file_path}"


