#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
# "loguru",
# ]
# ///
"""sets up your gitignore file with some common entries"""

from typing import List

from dataclasses import dataclass

import os
from pathlib import Path
import re
import sys

from loguru import logger

GITIGNORE = ".gitignore"

ALWAYS_ADD = [
    ".vscode/",
    ".DS_Store",
    ".env",
    ".envrc",  # direnv config
]

IF_EXISTS_ADD = [
    "*.asc",  # gpg files
]


@dataclass
class FileMatcher:
    language: str
    regex: str
    files: list[str]


# if the key regex matches filenames in the directory, add these
FILE_MATCHERS: List[FileMatcher] = [
    FileMatcher(language="Terraform", regex=r"\.tf$", files=["terraform.tfstate*", ".terraform/"]),
    FileMatcher(
        language="Python",
        regex=r"^(\.venv|pyproject\.toml|.py)$",
        files=[
            "build/",
            "dist/",
            "*.pyc",
            "*.egg-info/",
            "**/__pycache__/*",
            ".venv",
        ],
    ),
    FileMatcher(language="Python", regex=r"^config\.py$", files=["config.py"]),
    FileMatcher(language="Rust", regex=r"^Cargo\.toml", files=["target/"]),
]


def ask_question() -> str:
    """asks the user if they want to create a .gitignore file"""
    logger.info("Do you want to create {}? (y/n) ", GITIGNORE)
    return input().lower().strip()


# check we're in a git dir
if not os.path.exists("./.git/"):
    logger.error("You're not in a git repository, quitting.")
    sys.exit(1)

try:
    # check if the user wants to create a .gitignore file
    if not os.path.exists(GITIGNORE):
        logger.debug("{} doesn't exist", GITIGNORE)
        response = ask_question()
        while response not in ("y", "n"):
            response = ask_question()
        if response == "n":
            logger.info("Ok, quitting")
            sys.exit(1)
        Path(GITIGNORE).touch(mode=0o644, exist_ok=True)
except KeyboardInterrupt:
    sys.exit(0)


def read_file() -> list[str]:
    """reads the .gitignore file"""
    with open(GITIGNORE, encoding="utf8") as file_handle:
        return [line.strip() for line in file_handle.readlines()]


filecontents = read_file()

# things we're going to add to the .gitignore file, if they're not already there
needtoadd = []

for line in ALWAYS_ADD:
    if line not in filecontents and line not in needtoadd:
        needtoadd.append(line)

for line in IF_EXISTS_ADD:
    if Path("./").glob(line):
        if line not in filecontents and line not in needtoadd:
            needtoadd.append(line)

for matcher in FILE_MATCHERS:
    compiled_re = re.compile(matcher.regex)
    matched = any(compiled_re.match(filename) for filename in os.listdir("./"))
    if matched:
        logger.info("Found {} files", matcher.language)
        newlines = []
        for line in matcher.files:
            if line not in filecontents and line not in needtoadd:
                newlines.append(line)
        if newlines:
            logger.info("Adding {} lines for {}: {}", len(newlines), matcher.language, newlines)
            needtoadd.extend(newlines)

if not needtoadd:
    logger.info("File is OK!")
    sys.exit()

logger.info("Adding the following lines:")
with open(GITIGNORE, "a", encoding="utf8") as gitignore_fh:
    for line in needtoadd:
        logger.info(line)
    joined = "\n".join(needtoadd)
    try:
        gitignore_fh.write(f"\n{joined}\n")
    except Exception as e:
        logger.error("Error writing to file: {}", e)
        sys.exit(1)
