#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
# "click", "requests", "loguru"
# ]
# ///

from pathlib import Path
from hashlib import sha256
import sys
from typing import Dict, Any, List
import json
import click
import requests
from loguru import logger

JSON_PREFIX = '.streamController.enqueue("'


def extract_json(input_text: str) -> List[Any]:
    # find the first index of the JSON prefix
    prefix_index = input_text.find(JSON_PREFIX)

    end_script_index = input_text.find('\\n");</script>', prefix_index)
    if end_script_index != -1:
        input_text = input_text[:end_script_index]
    else:
        raise ValueError("End of script tag not found in input text")
    if prefix_index == -1:
        raise ValueError("JSON prefix not found in input text")
    # extract the JSON string starting from the prefix
    json_string_everything = input_text[prefix_index + len(JSON_PREFIX) :]
    json_string_everything = json_string_everything.encode().decode("unicode_escape")

    try:
        res: Dict[str, Any] = json.loads(json_string_everything)
        return res
    except json.JSONDecodeError:
        logger.debug("Failed to parse JSON")
        logger.debug(json_string_everything)
        raise ValueError("Failed to parse JSON from input text")


class CacheUrl:
    def __init__(self, url: str) -> None:
        self.url = url
        self.hash = sha256(url.encode()).hexdigest()
        self.cache_dir = Path.home() / ".cache" / "sbs-dlp"
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.cache_file = self.cache_dir / self.hash

        if not self.cache_file.exists():
            try:
                response = requests.get(url, timeout=30)
                response.raise_for_status()
                self.cache_file.write_text(response.text, encoding="utf-8")
            except Exception as error:
                logger.error(f"Error fetching URL: {error}")
                raise
        else:
            logger.debug(f"Using cached response for URL: {url}")

    def __str__(self) -> str:
        return self.cache_file.read_text(encoding="utf-8")


@click.command()
@click.argument("url")
@click.option("--debug", is_flag=True, help="Enable debug logging")
def main(url: str, debug: bool) -> None:
    logger.remove()
    if debug:
        logger.add(sys.stderr, level="DEBUG")
    else:
        logger.add(sys.stderr, level="INFO")
    response = CacheUrl(url)

    jsondata = extract_json(str(response))
    logger.debug(json.dumps(jsondata, indent=2))

    for index, element in enumerate(jsondata):
        if element == "seasons":
            logger.debug(f"Found seasons at index {index}")
            seasons = jsondata[index + 1]
            logger.debug(f"Seasons: {seasons}")

    if not seasons:
        logger.error("Seasons not found in JSON data")
        sys.exit(1)

    key_names = {
        "_25": "object_type",
        "_27": "object_name",
        "_29": "object_slug",
        "_23": "object_id",
        "_292": "season_number",
        "_297": "episode_row_index",
        "_172": "episode_row_index",
        "_325": "alternate_title",
        "_31": "description",
        "_183": "length",
        "_35": "date_row_references",
        "_320": "rating",
        "_188": "media_id",
        "_317": "show_name",
        "_318": "show_slug",
        "_319": "episode_number",
    }

    for season_row_id in seasons:
        season_data = {}
        for key, row_ref in jsondata[season_row_id].items():  # because it's a dict of data
            value = jsondata[row_ref]
            logger.debug(key, value)
            season_data[key_names.get(key, key)] = value
        logger.debug("Season data: {}", json.dumps(season_data, indent=2))

        if "episode_row_index" in season_data:
            for episode_row_id in season_data["episode_row_index"]:
                episode_data = {}
                for key, row_ref in jsondata[episode_row_id].items():
                    value = jsondata[row_ref]
                    logger.debug(key, value)
                    episode_data[key_names.get(key, key)] = value
                logger.debug("Episode data: {}", json.dumps(episode_data, indent=2))

                episode_url = f"https://www.sbs.com.au/ondemand/tv-series/{episode_data['show_slug']}/season-{episode_data['season_number']}/{episode_data['show_slug']}/{episode_data['media_id']}"
                print(episode_url)


if __name__ == "__main__":
    main()
