#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
# "click", "requests", "loguru"
# ]
# ///

from dotfiles.sbs_dlp import main


if __name__ == "__main__":
    main()
