#!/bin/bash

docker info >/dev/null 2>/dev/null || { echo "Docker is not running. Please start Docker and try again." >&2; exit 1; }

MYDIR=$(dirname "$0")
CONTAINER_NAME="returntocorp/semgrep:latest"
uv run --project "$MYDIR" "$MYDIR/docker-pull-latest-ish.py" "$CONTAINER_NAME"

if [ -f .semgreprc ]; then
    SEMGREP_EXTRAS=$(cat .semgreprc | sed -E 's/^\s*#.*$//g' | tr '\n' ' ')
else
    SEMGREP_EXTRAS=""
fi


# shellcheck disable=SC2068,SC2086
docker run --rm -it -v "${PWD}:/src" \
    "$CONTAINER_NAME" \
    semgrep ci --config auto \
    --exclude-rule "yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha" $SEMGREP_EXTRAS $@
