#!/bin/bash

# shellcheck disable=SC2068
docker run --rm -it -v "${PWD}:/src" \
    returntocorp/semgrep \
    semgrep ci --config auto \
    --exclude-rule "yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha" $@
