#!/bin/bash


if [ -z "$1" ]; then
  echo "Using 'latest' splunk version"
    VERSION="latest"
else
    VERSION="$1"
fi

ADMIN_PASSWORD="HelloWorld123"

NAME="splunk-$(basename "$(pwd)")"

echo "Mounting $(pwd) as /data in splunk/splunk:$VERSION container with password $ADMIN_PASSWORD"
docker run --rm -it --platform linux/amd64 \
    --name "$NAME" \
    --detach \
    --mount "type=bind,src=$(pwd),target=/data" \
    -e SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com \
    -e SPLUNK_START_ARGS=--accept-license \
    -e "SPLUNK_PASSWORD=${ADMIN_PASSWORD}" \
    -p 8000:8000 \
    -p 8089:8089 \
    -p 8088:8088 \
    "splunk/splunk:$VERSION"

docker logs -f "$NAME"