#!/bin/bash

set -e

TIME_MACHINE_DRIVE_FILE="$HOME/.config/timemachinedrive"

if [ ! -f "$TIME_MACHINE_DRIVE_FILE" ]; then
    echo "Can't find file $TIME_MACHINE_DRIVE_FILE"
    exit 1
fi
DRIVE="$(tr -d \\n < "${TIME_MACHINE_DRIVE_FILE}")"
echo "Using drive '${DRIVE}'" > /dev/stderr
# startbackup -b is "blocking" mode

diskutil mount "${DRIVE}" && \
    tmutil startbackup -b && \
    diskutil eject "${DRIVE}"
